name: Helm & Helmfile Action
description: Setup Helm and plugins, update repositories and applies configuration
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  helm-version:
    default: 3.11.2
    description: Helm version
    required: false
  helm:
    default: ''
    description: Helm command arguments
    required: false
  values:
    default: ''
    description: Values in multiline string defined as key=value
    required: false
  quiet:
    default: 'true'
    description: Disabled output on plugin installation & download actions
    required: false
  repository-config:
    default: repositories.yaml
    description: Path to the file containing Helm repository names and URLs
    required: false
  helmfile-version:
    default: 0.152.0
    description: Helmfile version
    required: false
  helmfile:
    default: ''
    description: Helmfile command arguments
    required: false
  helmfile-config:
    default: helmfile.yaml
    description: Load config from file or directory.
    required: false
  namespace:
    default: ''
    required: false
    description: Kubernetes namespace scope for this request
  environment:
    default: ''
    required: false
    description: Specify the environment name
  selectors:
    default: ''
    required: false
    description: Comma-separated key-value pairs of labels (e.g. foo=bar or foo!=bar)
  kube-context:
    default: ''
    required: false
    description: Set kubectl context. Uses current context by default
  log-level:
    default: info
    required: false
    description: Set log level
  plugins:
    default: secrets,diff
    required: false
    description: Helm plugins to install
outputs: {}
runs:
  using: node16
  main: src/index.js
